/**
 * GEON'S GAMEHUB - storyData.js
 * Story Quiz content: the ten documented stories, each with a passage and
 * five comprehension questions using the documented question types:
 * detail, setting, sequence, inference, reasonable inference.
 */
export const STORIES = Object.freeze([
  {
    id: 'lost-compass',
    title: 'The Lost Compass',
    passage: `Mang Tonyo lent his old brass compass to his granddaughter Iris before her first mountain hike with the school club. "Your lolo used this on the trail to Baguio," he said. "Bring it home safe." Halfway up the slope, Iris stopped to tie her shoelace and set the compass on a mossy rock. When the group moved on, she forgot it. Two kilometers later, she patted her pocket and felt nothing. Her chest tightened. The trail forked ahead, and without the compass, the fog suddenly felt thicker. Iris remembered her leader's advice: retrace your steps one landmark at a time. She walked back past the twisted pine, then the fallen log, until she saw the mossy rock glinting faintly in the gray light. The compass was exactly where she had left it. That night, she returned it to Mang Tonyo and promised to zip it inside her bag from then on.`,
    questions: [
      { type: 'detail', question: 'Who originally used the compass on the trail to Baguio?', choices: ["Iris's lolo", 'Mang Tonyo', "Iris's teacher", "Iris's classmate"], answer: "Iris's lolo", explanation: 'Mang Tonyo said, "Your lolo used this on the trail to Baguio."' },
      { type: 'setting', question: 'Where does most of the story take place?', choices: ['On a mountain hiking trail', 'Inside a school classroom', 'At a city market', 'On a boat at sea'], answer: 'On a mountain hiking trail', explanation: 'The events happen on a foggy mountain slope during a school club hike.' },
      { type: 'sequence', question: 'What happened immediately after Iris set the compass on the mossy rock?', choices: ['The group moved on and she forgot it', 'She zipped it into her bag', 'Mang Tonyo called her', 'The fog cleared away'], answer: 'The group moved on and she forgot it', explanation: 'Right after she placed it on the rock to tie her shoelace, the group moved on and she forgot it.' },
      { type: 'inference', question: 'Why did Iris feel her chest tighten when she patted her pocket?', choices: ['She realized she had lost something precious to her grandfather', 'She was excited about the fork in the trail', 'She was angry at her leader', 'She felt cold from the fog only'], answer: 'She realized she had lost something precious to her grandfather', explanation: 'The compass was a borrowed keepsake; discovering it gone caused fear and guilt, shown by her tightening chest.' },
      { type: 'reasonable inference', question: 'Based on the ending, what will Iris most likely do on future hikes?', choices: ['Keep the compass secured inside her bag', 'Leave the compass at home forever', 'Give the compass to her leader', 'Buy a plastic compass instead'], answer: 'Keep the compass secured inside her bag', explanation: 'She promised to zip it inside her bag, so she will most likely keep valuables secured from then on.' },
    ],
  },
  {
    id: 'hidden-valley',
    title: 'The Hidden Valley',
    passage: `Behind the rice terraces of Baroy, a narrow gap between two cliffs hid a small valley that appeared on no map. The elders called it Lunas, the meadow that breathes. Every April, wild sunflowers filled it edge to edge, and bees hummed so loudly the air seemed to vibrate. A developer heard rumors of the valley and offered to buy the gap land for a resort. The barangay council debated for weeks. Aling Nena, the oldest farmer, spoke last. "The bees pollinate our squash and beans," she said. "Cover Lunas with cement, and you will buy bricks with the money from vegetables we can no longer grow." The council voted to protect the valley as a community heritage site. Every April since, the school walks the children through the sunflowers, and the bees still hum over Baroy's vegetables.`,
    questions: [
      { type: 'detail', question: 'What do the elders call the hidden valley?', choices: ['Lunas', 'Baroy', 'Nena', 'Terrace'], answer: 'Lunas', explanation: 'The elders called the valley Lunas, "the meadow that breathes."' },
      { type: 'setting', question: 'Where is the hidden valley located?', choices: ['Behind the rice terraces of Baroy, between two cliffs', 'In the middle of a busy city', 'Beside a highway', 'On an island far offshore'], answer: 'Behind the rice terraces of Baroy, between two cliffs', explanation: 'The story opens with the valley hidden behind Baroy\'s rice terraces in a gap between cliffs.' },
      { type: 'sequence', question: 'What happened right after the developer offered to buy the land?', choices: ['The barangay council debated for weeks', 'The school took children to the valley', 'Aling Nena planted sunflowers', 'The resort construction began'], answer: 'The barangay council debated for weeks', explanation: 'The offer triggered weeks of council debate before Aling Nena spoke and the vote followed.' },
      { type: 'inference', question: 'Why did Aling Nena mention squash and beans in her speech?', choices: ['To show the valley supports the farmers through bee pollination', 'To advertise vegetables for sale', 'To complain about her garden', 'To change the subject away from the resort'], answer: 'To show the valley supports the farmers through bee pollination', explanation: 'She connected the bees in Lunas to the pollination of their crops - destroying the valley would destroy their livelihood.' },
      { type: 'reasonable inference', question: 'What will most likely happen every April now?', choices: ['Students will visit the protected sunflower valley', 'The valley will be sold to the developer', 'The bees will leave Baroy', 'The council will ban visitors'], answer: 'Students will visit the protected sunflower valley', explanation: 'The valley became a heritage site and the school already walks children through it each April - this will most likely continue.' },
    ],
  },
  {
    id: 'lighthouse-signal',
    title: 'The Lighthouse Signal',
    passage: `For thirty years, Kap Danding climbed the ninety-one steps of the Capones lighthouse every evening. Fishermen in the cove did not own radios; they read the light instead. Three slow flashes meant calm seas. Two quick flashes followed by a pause meant strong current - stay near the shore. One long unbroken beam meant storm; do not leave the harbor. One November night, the generator coughed and died. Kap Danding was old and his knees ached, but the weather report had warned of a storm. He carried kerosene up the ninety-one steps, filled the backup lamp by trembling hands, and lit it. The long beam swept the water just as the first fishing boats turned toward home. Every boat returned that night. The next morning, the fishermen carried sacks of fish up to the lighthouse - their way of saying thank you without words.`,
    questions: [
      { type: 'detail', question: 'What did three slow flashes of the lighthouse mean?', choices: ['Calm seas', 'Strong current', 'Storm warning', 'Time to return home'], answer: 'Calm seas', explanation: 'The story states three slow flashes meant calm seas.' },
      { type: 'setting', question: 'Where does the story take place?', choices: ['At a seaside lighthouse and fishing cove', 'In a mountain village', 'Inside a city hospital', 'On a large cargo ship'], answer: 'At a seaside lighthouse and fishing cove', explanation: 'Kap Danding works in the Capones lighthouse above a fishing cove.' },
      { type: 'sequence', question: 'What did Kap Danding do immediately after the generator died?', choices: ['He carried kerosene up the steps to light the backup lamp', 'He called the coast guard on the radio', 'He went to sleep until morning', 'He swam out to warn the boats'], answer: 'He carried kerosene up the steps to light the backup lamp', explanation: 'After the generator failed, he carried kerosene up ninety-one steps and lit the backup lamp.' },
      { type: 'inference', question: 'Why did the fishermen bring sacks of fish to the lighthouse?', choices: ['To thank Kap Danding for the light that guided them home safely', 'To sell fish at the lighthouse', 'To ask him to repair their boats', 'To complain about the light signals'], answer: 'To thank Kap Danding for the light that guided them home safely', explanation: 'The story says the fish were "their way of saying thank you without words" after every boat returned.' },
      { type: 'reasonable inference', question: 'Based on the passage, what is TRUE about the fishermen and the lighthouse?', choices: ['They depend on the light signals because they have no radios', 'They prefer sailing during storms', 'They never fish in November', 'They maintain the generator themselves'], answer: 'They depend on the light signals because they have no radios', explanation: 'The passage says the fishermen "did not own radios; they read the light instead."' },
    ],
  },
  {
    id: 'library-window',
    title: 'The Library Window',
    passage: `The public library of San Isidro closed at five, but its tall side window stayed cracked open for ventilation. Every evening after his shift at the vulcanizing shop, Jun stood outside that window and read whatever book lay open on the return cart. The librarian, Miss Celia, noticed his worn uniform and his careful lips moving over the words. One rainy Tuesday, she left the cart closer to the window. The next week, she left a small lamp aimed at the cart. In December, she simply left the side door unlocked with a note taped inside: "Reading has no closing time. - C." Jun cried in the biography section where no one would see him. Years later, a plaque in that library reads: "This building expanded its evening hours in honor of every reader who refused to stop." Jun, now an engineer, cut the ribbon.`,
    questions: [
      { type: 'detail', question: 'What time did the library close?', choices: ['Five o\u2019clock', 'Seven o\u2019clock', 'Noon', 'Nine o\u2019clock'], answer: 'Five o\u2019clock', explanation: 'The first line says the library closed at five.' },
      { type: 'setting', question: 'Where did Jun read every evening at the start of the story?', choices: ['Outside the cracked library window', 'Inside the reading room', 'At his shop counter', 'Under a streetlamp at home'], answer: 'Outside the cracked library window', explanation: 'Jun stood outside the tall side window reading books from the return cart.' },
      { type: 'sequence', question: 'What did Miss Celia do BEFORE leaving the door unlocked?', choices: ['She moved the cart closer to the window and added a lamp', 'She gave Jun a library card', 'She closed the window permanently', 'She asked Jun to leave'], answer: 'She moved the cart closer to the window and added a lamp', explanation: 'First the cart moved closer (rainy Tuesday), then the lamp (next week), and only in December came the unlocked door.' },
      { type: 'inference', question: 'Why did Jun cry in the biography section?', choices: ['He was deeply moved by finally being welcomed as a reader', 'He was sad the library would close forever', 'He failed an engineering exam', 'He was allergic to old books'], answer: 'He was deeply moved by finally being welcomed as a reader', explanation: 'The note welcoming him ("Reading has no closing time") moved him to tears; he hid where no one would see.' },
      { type: 'reasonable inference', question: 'What does the plaque suggest about Jun\u2019s effect on the library?', choices: ['His example helped extend the library\u2019s evening hours for all readers', 'He donated the whole building', 'He worked as the night librarian', 'He banned evening reading'], answer: 'His example helped extend the library\u2019s evening hours for all readers', explanation: 'The plaque honors "every reader who refused to stop" and mentions expanded evening hours - inspired by readers like Jun.' },
    ],
  },
  {
    id: 'rain-garden',
    title: 'The Rain Garden Plan',
    passage: `Every heavy rain, the creek behind Maligaya Elementary overflowed into the schoolyard. Mud ruined the flag ceremony, and classes sometimes suspended early. The Grade 6 class decided to act. Their teacher, Sir Ambo, introduced the idea of a rain garden: a shallow planted basin that captures runoff and lets it soak slowly into the ground instead of rushing into the creek. The students measured the slope, sketched a plan, and presented it to the barangay captain. "Plants that drink floods?" she laughed, but she approved ten bags of soil. The class planted vetiver grass, kangkong beds, and ornate taro in terraced rows. When the August storms came, the garden held. The creek still rose, but the schoolyard dried by noon. The barangay captain returned - not laughing this time - and asked for copies of the students' plan for the other two schools.`,
    questions: [
      { type: 'detail', question: 'Which plants did the students put in their rain garden?', choices: ['Vetiver grass, kangkong, and ornate taro', 'Rice and corn', 'Mango and coconut', 'Roses and sunflowers only'], answer: 'Vetiver grass, kangkong, and ornate taro', explanation: 'The passage lists vetiver grass, kangkong beds, and ornate taro in terraced rows.' },
      { type: 'setting', question: 'Where is the story set?', choices: ['At Maligaya Elementary and the creek behind it', 'At a university in the city', 'On a fishing pier', 'Inside a botanical greenhouse'], answer: 'At Maligaya Elementary and the creek behind it', explanation: 'The overflow problem and the garden happen at Maligaya Elementary beside the creek.' },
      { type: 'sequence', question: 'What happened immediately after the students presented their plan?', choices: ['The barangay captain approved ten bags of soil', 'The August storms arrived', 'The garden was already full-grown', 'Classes were suspended for a month'], answer: 'The barangay captain approved ten bags of soil', explanation: 'After the presentation, she laughed but approved ten bags of soil; planting came next.' },
      { type: 'inference', question: 'What can you infer about the barangay captain at the end?', choices: ['She changed her mind and respected the students\u2019 solution', 'She remained doubtful about rain gardens', 'She wanted to stop the project', 'She never returned to the school'], answer: 'She changed her mind and respected the students\u2019 solution', explanation: 'She returned "not laughing this time" and asked for copies of the plan - clear evidence of changed respect.' },
      { type: 'reasonable inference', question: 'Why did the schoolyard dry by noon after the storms?', choices: ['The rain garden captured runoff and let it soak into the ground slowly', 'The creek stopped flowing completely', 'Janitors mopped the whole yard', 'The rain stopped earlier that year'], answer: 'The rain garden captured runoff and let it soak into the ground slowly', explanation: 'The garden worked as designed: capturing runoff so the yard drained much faster than before.' },
    ],
  },
  {
    id: 'clockmaker-note',
    title: "The Clockmaker's Note",
    passage: `When Lola Remedios passed away, her family found the old shop clock she had wound every Sunday for forty years. Taped inside its back panel was a folded note in her handwriting: "To whoever winds this clock - it is not about the time it tells. It is about the person who keeps showing up. Wind it gently. Show up gently. That is all a life is." Her grandson Nico, a college student who changed his course three times and quit his part-time jobs twice, read the note by the window for a long time. He hung the clock in his boarding-house room. He set a phone alarm for Sunday evenings. Some weeks he forgot; some weeks he was too tired. But he climbed the chair and turned the small brass key anyway. Four years later, Nico graduated. In his acceptance speech he thanked a teacher he never met: a clockmaker who taught him that consistency is a form of love.`,
    questions: [
      { type: 'detail', question: 'How often did Lola Remedios wind the shop clock?', choices: ['Every Sunday', 'Every morning', 'Once a month', 'Every New Year'], answer: 'Every Sunday', explanation: 'She wound the clock every Sunday for forty years.' },
      { type: 'setting', question: 'Where did Nico hang the clock?', choices: ['In his boarding-house room', 'Back in the old shop', 'In his classroom', 'At the city museum'], answer: 'In his boarding-house room', explanation: 'After reading the note, Nico hung the clock in his boarding-house room.' },
      { type: 'sequence', question: 'What happened FIRST in the story?', choices: ['The family found the clock and the note after Lola Remedios passed away', 'Nico gave his acceptance speech', 'Nico set the Sunday alarm', 'Nico graduated college'], answer: 'The family found the clock and the note after Lola Remedios passed away', explanation: 'The discovery of the clock and note after her death opens the story; everything else follows.' },
      { type: 'inference', question: 'What did the note mean by "the person who keeps showing up"?', choices: ['That consistency and commitment matter more than talent or results', 'That visitors should come every Sunday', 'That clocks need repair shops', 'That time moves too fast'], answer: 'That consistency and commitment matter more than talent or results', explanation: 'The note values showing up gently and regularly - Nico understood it as consistency being the real lesson.' },
      { type: 'reasonable inference', question: 'Why did Nico call his grandmother "a teacher he never met" in his speech?', choices: ['Because her note taught him the habit of consistency that carried him to graduation', 'Because she was a professor at his college', 'Because she taught clockmaking classes', 'Because he never saw her face'], answer: 'Because her note taught him the habit of consistency that carried him to graduation', explanation: 'He never met her (she passed before his college years shaped him), yet her lesson guided him to finish.' },
    ],
  },
  {
    id: 'bridge-of-paper',
    title: 'The Bridge of Paper',
    passage: `The engineering club's annual challenge was deceptively simple: build a bridge out of twenty sheets of newspaper and one roll of tape that could hold a one-kilo weight. The veterans rolled tight paper tubes and lashed them into triangles. Maya, a first-year member, had failed the tryout quiz and nearly did not join. She watched the seniors, then noticed something: their joints wobbled because the tubes were bound only at the ends. She proposed binding every joint with a thin paper collar. "Too slow," said the team captain. "We will lose time." Maya asked for the leftover sheets. Alone in the corner, she built a small test span with collared joints. When the testing day came, the veterans' bridge sagged at forty seconds. Maya's small bridge held the weight for five full minutes. The captain handed her the team's flag for next year's competition and said, "Test before you dismiss."`,
    questions: [
      { type: 'detail', question: 'What materials were allowed in the bridge challenge?', choices: ['Twenty sheets of newspaper and one roll of tape', 'Wood planks and nails', 'Straws and glue guns', 'Cardboard and string only'], answer: 'Twenty sheets of newspaper and one roll of tape', explanation: 'The rules allowed twenty sheets of newspaper and one roll of tape.' },
      { type: 'setting', question: 'Where does the competition take place?', choices: ['In a school engineering club setting', 'At a city construction site', 'On a river between two towns', 'In a paper factory'], answer: 'In a school engineering club setting', explanation: 'The annual challenge belongs to the school engineering club, with members and tryouts.' },
      { type: 'sequence', question: 'What did Maya do right after the captain rejected her idea?', choices: ['She asked for the leftover sheets and built a small test span', 'She quit the club immediately', 'She rebuilt the veterans\u2019 bridge herself', 'She complained to the adviser'], answer: 'She asked for the leftover sheets and built a small test span', explanation: 'After "too slow," she requested leftovers and tested her collared-joint design alone.' },
      { type: 'inference', question: 'What does the captain\u2019s final line "Test before you dismiss" mean?', choices: ['Ideas should be examined with evidence before being rejected', 'Bridges must be tested for five minutes', 'New members should not speak', 'Time limits do not matter in contests'], answer: 'Ideas should be examined with evidence before being rejected', explanation: 'He learned that dismissing Maya\u2019s untested idea cost them the win; ideas deserve a test first.' },
      { type: 'reasonable inference', question: 'What will most likely happen next year?', choices: ['Maya will lead the team in the next competition', 'Maya will fail the tryout again', 'The club will ban paper bridges', 'The captain will refuse to compete'], answer: 'Maya will lead the team in the next competition', explanation: 'The captain handed her the team flag for next year - the symbol of leadership.' },
    ],
  },
  {
    id: 'orchard-map',
    title: 'The Orchard Map',
    passage: `Before he lost his sight, Tatay Berting drew a map of the family orchard: thirty-two mango trees in eight rows, each tree numbered and named after a relative. "Tree 12 is your mother," he told his son Elmer. "She fruits early and sweet." Years after the illness darkened his world, the orchard fell into neglect until Elmer, now grown, found the map inside a rusted biscuit tin. He walked the rows with the map in one hand and his father's words in memory. Tree by tree, he pruned, watered, and grafted. When the first harvest came, he placed the biggest mango in his father's palm. Tatay Berting held it to his nose and smiled. "Tree 12," he said. "Your mother." He could not see the fruit, but forty years of mornings in the orchard had taught his hands and heart exactly what home smelled like.`,
    questions: [
      { type: 'detail', question: 'How many mango trees were in the orchard?', choices: ['Thirty-two trees in eight rows', 'Twelve trees in four rows', 'Forty trees in ten rows', 'Twenty trees in five rows'], answer: 'Thirty-two trees in eight rows', explanation: 'The map showed thirty-two mango trees arranged in eight rows.' },
      { type: 'setting', question: 'Where is the story centered?', choices: ['At the family mango orchard', 'In a hospital ward', 'At a city fruit market', 'Inside a biscuit factory'], answer: 'At the family mango orchard', explanation: 'The orchard and its rows are the heart of the story, past and present.' },
      { type: 'sequence', question: 'What did Elmer do immediately after finding the map in the biscuit tin?', choices: ['He walked the rows and began restoring the trees one by one', 'He sold the orchard to a neighbor', 'He planted thirty-two new trees', 'He gave the map back to his father'], answer: 'He walked the rows and began restoring the trees one by one', explanation: 'With map in hand, he walked the rows and pruned, watered, and grafted tree by tree.' },
      { type: 'inference', question: 'Why was Tatay Berting able to identify the mango as "Tree 12" without seeing it?', choices: ['Its smell and feel were familiar from decades in the orchard', 'Elmer whispered the answer to him', 'The mango had a numbered sticker', 'He could see shadows of the fruit'], answer: 'Its smell and feel were familiar from decades in the orchard', explanation: 'The closing lines explain that forty years of orchard mornings trained his hands and heart to recognize it by smell.' },
      { type: 'reasonable inference', question: 'Why were the trees named after relatives?', choices: ['The orchard was a living family memorial and expression of love', 'The relatives owned separate farms', 'Mango varieties carry family surnames by law', 'The names helped buyers pay more'], answer: 'The orchard was a living family memorial and expression of love', explanation: 'Naming each tree after a relative (his wife is Tree 12) shows the orchard held the family\u2019s memory and affection.' },
    ],
  },
  {
    id: 'signal-lantern',
    title: 'The Signal Lantern',
    passage: `During the yearly flood season, the families of Riverside Street agreed on a lantern code. A red lantern in the window meant water was rising fast - move to the second floor. A white lantern meant the crossing bridge was safe. No lantern meant evacuate to the school gym immediately. One September night, the power failed across the whole street, and the river rose faster than anyone expected. Aling Rosing, whose window faced the whole street, climbed to her attic with her late husband's kerosene lantern. She had no red glass shade, so she wrapped the chimney in her red duster. The crimson glow spread across the flooded street, and family after family saw the warning and climbed to their second floors. By morning, the water reached the first-floor ceilings - but every family on Riverside Street was safe and dry upstairs, watching the red lantern flicker like a stubborn heartbeat.`,
    questions: [
      { type: 'detail', question: 'What did a white lantern in the window mean?', choices: ['The crossing bridge was safe', 'Water was rising fast', 'Evacuate to the gym', 'The power would return soon'], answer: 'The crossing bridge was safe', explanation: 'The code: white lantern = bridge safe; red = rising water; none = evacuate.' },
      { type: 'setting', question: 'Where does the story take place?', choices: ['On Riverside Street during flood season', 'On a ship during a typhoon', 'In a mountain village during summer', 'At the school gym during a fiesta'], answer: 'On Riverside Street during flood season', explanation: 'The lantern code belongs to the families of Riverside Street during the yearly floods.' },
      { type: 'sequence', question: 'What did Aling Rosing do right after the power failed and the river rose?', choices: ['She wrapped the lantern chimney in her red duster and showed the red warning', 'She called the coast guard by phone', 'She evacuated alone to the gym', 'She waited for morning light'], answer: 'She wrapped the lantern chimney in her red duster and showed the red warning', explanation: 'Lacking a red shade, she improvised with her red duster and raised the warning light.' },
      { type: 'inference', question: 'Why did the families climb to their second floors that night?', choices: ['They understood the red lantern warning and acted on it', 'They wanted to watch the river for fun', 'The first floors were under repair', 'The gym was too far for everyone'], answer: 'They understood the red lantern warning and acted on it', explanation: 'The red light meant "rising water - go upstairs," and family after family followed the agreed code.' },
      { type: 'reasonable inference', question: 'What does the story suggest about community agreements like the lantern code?', choices: ['Simple shared plans can save lives during disasters', 'Lanterns are better than all technology always', 'Floods cannot harm second floors', 'Only elders should make safety plans'], answer: 'Simple shared plans can save lives during disasters', explanation: 'A simple agreed code, executed calmly, kept every family safe when modern power failed.' },
    ],
  },
  {
    id: 'museum-key',
    title: 'The Museum Key',
    passage: `The small town museum of Angono kept one locked cabinet that no docent could open. The old curator, Manong Felix, always said, "The key exists. It simply waits for the right question." Visitors guessed combinations, jiggled handles, and gave up. A grade schooler named Pat stayed behind after a tour and asked, "Manong, what is INSIDE?" Felix's eyes lit up. He told her the cabinet held the town's first flag, sewn by the women of Angono during the revolution - but the cloth was too fragile for the bright hall. "Light is its enemy," he said. Pat thought for a moment. "Then the right question is not how to open it, but how to show it without light hurting it." Felix smiled and pulled a small brass key from his pocket. Together they planned a darkened viewing room with a timed, gentle lamp. On the museum's fiftieth year, Pat - now its curator - opened the cabinet for the town, and the fragile flag finally met the people it was sewn for.`,
    questions: [
      { type: 'detail', question: 'What was kept inside the locked cabinet?', choices: ['The town\u2019s first flag, sewn during the revolution', 'Gold coins from the Spanish era', 'Old museum tickets', 'The curator\u2019s diary'], answer: 'The town\u2019s first flag, sewn during the revolution', explanation: 'Felix said the cabinet held the town\u2019s first flag, sewn by the women of Angono during the revolution.' },
      { type: 'setting', question: 'Where does the story take place?', choices: ['In the small town museum of Angono', 'In a school library', 'In a city shopping mall', 'In a flag factory'], answer: 'In the small town museum of Angono', explanation: 'The events unfold inside the small town museum of Angono.' },
      { type: 'sequence', question: 'What happened right after Pat asked what was inside the cabinet?', choices: ['Felix explained about the fragile flag and said light was its enemy', 'He gave her the key instantly without talking', 'The cabinet opened by itself', 'He asked her to leave the museum'], answer: 'Felix explained about the fragile flag and said light was its enemy', explanation: 'Her question made his eyes light up, and he then told her about the flag and its fragility.' },
      { type: 'inference', question: 'What did Manong Felix mean by "the key waits for the right question"?', choices: ['Only someone who truly cared about protecting the flag deserved to open it', 'The key was physically hidden in a question book', 'Visitors must pay to get answers', 'The lock changes its combination daily'], answer: 'Only someone who truly cared about protecting the flag deserved to open it', explanation: 'Pat\u2019s question showed she cared about the flag\u2019s safety, not just curiosity - that is why he trusted her with the key.' },
      { type: 'reasonable inference', question: 'Why was a darkened room with a timed lamp planned for the flag?', choices: ['To display the flag while limiting damaging light exposure', 'To save electricity bills', 'To make visitors afraid', 'Because flags must be viewed at night only'], answer: 'To display the flag while limiting damaging light exposure', explanation: 'Light was the flag\u2019s enemy, so a dark room with brief gentle lighting protects it while letting people see it.' },
    ],
  },
]);

export function storyById(id) {
  return STORIES.find((s) => s.id === id) || null;
}

export function storyCount() {
  return STORIES.length;
}
