"""
GEON'S GAMEHUB - expansion fact pools.

Extra hand-written facts so the Previous and New questioners can draw
mostly-disjoint content, plus procedural numeric generators for
Pascal's Principle and Archimedes' Principles calculations.
Same tuple format as tools/pools.py.
"""

ARCH_EXTRA = [
    ("A rock weighs 12 N in air and 9 N underwater. What buoyant force acts on it?", "3 N",
     ["12 N", "9 N", "21 N"],
     "Buoyant force = weight in air - apparent weight = 12 N - 9 N = 3 N.", None),
    ("Which action increases the buoyant force on a submerged ball?", "Submerging a larger ball",
     ["Painting the ball", "Using a darker ball", "Warming the ball slightly"],
     "Bigger volume displaces more fluid, which increases buoyant force.", None),
    ("A cargo ship unloads containers at port. What happens to how deep it sits?", "It rises because it needs to displace less water",
     ["It sits lower", "Nothing changes", "It sinks slightly"],
     "Less weight means less water needs displacing, so the hull rises in the water.", None),
    ("Why do swimmers float more easily in the ocean than in a freshwater pool?", "Salt water is denser and gives more buoyant force",
     ["Ocean water is warmer only", "Pools have weaker gravity", "Salt water has less water"],
     "Higher density fluid means each displaced liter weighs more, boosting buoyancy.", None),
    ("Which instrument measures whether milk has been watered down using buoyancy?", "A lactometer (hydrometer type)",
     ["A thermometer", "A barometer", "A speedometer"],
     "A lactometer floats higher in denser pure milk, revealing added water.", None),
    ("A submerged object feels lighter because ____.", "Buoyant force pushes up against its weight",
     ["Gravity weakens underwater", "Water dissolves part of it", "Pressure removes mass"],
     "The upward buoyant force offsets part of the object's weight.", None),
    ("An object exactly as dense as water will ____.", "Hover (stay suspended) in the water",
     ["Float high on the surface", "Sink to the bottom fast", "Bounce on the surface"],
     "Equal densities mean weight and buoyant force balance at any depth.", None),
    ("Which design lets a small piece of steel 'float'?", "Shaping it into a hollow bowl",
     ["Melting it into a ball", "Cutting it in half", "Polishing it"],
     "A hollow shape displaces more water than its weight requires, creating enough buoyant force.", None),
    ("Buoyant force on a fully submerged object depends on ____.", "The fluid's density and the object's volume",
     ["The object's color and shape only", "How deep it is pushed (beyond full submersion)", "The time of day"],
     "Once fully submerged, buoyant force = fluid density x displaced volume x gravity - depth alone changes nothing.", None),
    ("A balloon underwater is squeezed smaller as it goes deeper. Its buoyant force ____.", "Decreases because it displaces less water",
     ["Increases", "Stays the same", "Becomes infinite"],
     "Smaller volume means less displaced water, so buoyant force drops.", None),
]

MIND_MANIP_EXTRA = [
    ("A person repeatedly gives you backhanded compliments ('nice shirt, for once'). This is meant to ____.", "Lower your confidence so you seek their approval",
     ["Genuinely compliment you", "Test your fashion sense", "Practice honesty"],
     "Backhanded compliments (negging) chip at self-esteem so the manipulator's approval feels more valuable.", None),
    ("Someone changes the subject every time you ask for evidence. This behavior ____.", "Avoids accountability and hides weak claims",
     ["Shows strong evidence", "Proves they are right", "Means they are busy"],
     "Dodging evidence questions is a deflection tactic; keep calmly returning to your question.", None),
    ("'After everything I did for you...' is a phrase used to ____.", "Create a debt you never agreed to",
     ["Give a sincere gift", "Offer real help", "Share happy memories"],
     "Weaponizing past favors pressures you into compliance through invented obligation.", None),
    ("Which is a red flag in online group pressure?", "Members punish questioning with mockery or exclusion",
     ["Members welcome respectful questions", "Rules are explained openly", "Leaving is allowed without threats"],
     "Healthy groups tolerate questions; cult-like groups punish doubt to keep control.", None),
    ("A scammer claims to be a bank officer needing your OTP 'to protect your account.' You should ____.", "Refuse - real banks never ask for OTPs",
     ["Share the OTP quickly", "Share half the code", "Ask them to call later with the OTP"],
     "One-time passwords are secrets; anyone asking for them is attempting fraud.", None),
    ("Someone says 'You're the only one who understands me' to speed intimacy. This is ____.", "A trust-accelerating manipulation line",
     ["A normal first-meeting fact", "A verified statement", "Random small talk"],
     "Special-bond claims rush closeness so requests follow before you can evaluate the person.", None),
    ("Which tactic hides real costs until after you commit?", "Bait-and-switch",
     ["Full disclosure upfront", "Written contracts", "Free trials with clear terms"],
     "Bait-and-switch lures with one offer, then swaps in worse terms after commitment.", None),
    ("'Everyone else already agreed, you're the only holdout.' Before deciding, you should ____.", "Verify independently whether that is true",
     ["Agree to avoid standing out", "Assume they are lying always", "Decide based on their tone"],
     "Claimed unanimity is often exaggerated to pressure the last dissenter.", None),
    ("Which response shows assertive (not aggressive) resistance?", "'I hear you, but my answer is no.'",
     ["'You're evil for asking!'", "Silent sulking for days", "'Yes...' while resenting it"],
     "Assertiveness states your position clearly and respectfully without attack or surrender.", None),
    ("A manipulator keeps asking the same favor many times, wearing you down. This is ____.", "Badgering / nagging pressure",
     ["Healthy persistence", "A one-time request", "Polite follow-up once"],
     "Repetition until you give in exploits exhaustion; a clear repeated 'no' ends it.", None),
    ("Which is TRUE about compliments from manipulators?", "They are often strategic tools timed before requests",
     ["They are always fake in every way", "They always come with gifts", "They are identical to honest praise"],
     "Watch patterns: praise that reliably precedes asks is tactical, not heartfelt.", None),
    ("Someone records your casual words and quotes them back aggressively later. The best protection is ____.", "Be mindful of what you share and set boundaries with untrustworthy people",
     ["Never speak at all", "Record everyone secretly always", "Assume all friends record you"],
     "Awareness and boundaries reduce exposure to people who weaponize your words.", None),
]

SELF_RES_EXTRA = [
    ("Which reaction to a friend's bad news is MOST supportive?", "Listening fully and asking what they need",
     ["Immediately sharing your own worse story", "Changing the subject to something fun", "Telling them to stop crying"],
     "Support starts with presence and listening; advice comes only when wanted.", None),
    ("What is 'behavioral activation' in coping with low mood?", "Scheduling small positive or meaningful activities even when unmotivated",
     ["Waiting for motivation before doing anything", "Isolating to recharge for weeks", "Avoiding all routines"],
     "Action often precedes motivation; small planned activities lift mood gradually.", None),
    ("Which is an example of healthy stress ('eustress')?", "The focused energy before a performance you prepared for",
     ["Constant panic for no reason", "Sleepless worry every night", "Numbness toward everything"],
     "Eustress is short-term arousal that improves performance; distress is chronic and harmful.", None),
    ("A student compares grades and feels hopeless. A balanced thought is ____.", "'Grades show current results, not my total ability or future.'",
     ["'I am my grades.'", "'Grades never matter at all.'", "'Others' success means my failure.'"],
     "Balanced thinking separates performance snapshots from identity and potential.", None),
    ("Which coping style tackles the problem itself rather than just the feelings?", "Problem-focused coping (planning, seeking info, acting)",
     ["Avoiding the issue entirely", "Only venting repeatedly", "Pretending the problem is gone"],
     "Problem-focused coping changes the stressor; emotion-focused coping manages feelings - both have their place.", None),
    ("What does 'progress over perfection' mean for resilience?", "Valuing steady improvement instead of flawless results",
     ["Never having standards", "Quitting when imperfect", "Only celebrating perfect wins"],
     "Sustainable growth comes from consistent imperfect action, not rare perfect performances.", None),
    ("Which habit helps you bounce back faster after a bad day?", "A short wind-down routine: tidy space, reflect briefly, sleep on time",
     ["Replaying the day angrily for hours", "Skipping sleep to 'make up' work", "Scrolling until exhausted"],
     "Closure routines signal the brain that the day is done, protecting tomorrow's energy.", None),
    ("When grief or sadness feels overwhelming for weeks, the wise step is ____.", "Talk to a trusted adult or counselor",
     ["Hide it and stay busy forever", "Self-medicate with junk food or games", "Wait years for it to pass alone"],
     "Persistent heavy feelings deserve professional support - reaching out is strength.", None),
    ("Which statement about emotions is TRUE?", "All emotions carry information, even uncomfortable ones",
     ["Anger and fear are useless always", "Only happy emotions are valid", "Emotions are weaknesses"],
     "Fear signals danger, anger signals crossed boundaries - emotions guide, they don't rule.", None),
    ("A resilient way to handle public embarrassment is ____.", "Acknowledge it lightly, learn any lesson, and move on",
     ["Replay it nightly for months", "Blame everyone who saw it", "Never appear in public again"],
     "Most people forget quickly; self-acceptance ends the loop fastest.", None),
    ("Which is a realistic affirmation style?", "'I can handle this step by step.'",
     ["'I am perfect at everything.'", "'Nothing can ever hurt me.'", "'I need no one.'"],
     "Believable affirmations support action; unrealistic ones collapse under first failure.", None),
    ("What helps prevent burnout while pursuing big goals?", "Scheduled rest, boundaries, and regular check-ins on workload",
     ["Working through every weekend forever", "Ignoring early fatigue signals", "Dropping all hobbies permanently"],
     "Burnout prevention is built into the schedule, not added after collapse.", None),
]

CONVINCE_EXTRA = [
    ("Which opening best grabs honest attention in a pitch?", "A surprising true fact or a relevant question",
     ["A long apology for speaking", "Insulting the current system", "Reading the title slowly"],
     "Genuine hooks (true surprises, relevant questions) earn attention without tricks.", None),
    ("What makes an example persuasive in an argument?", "It is real, relevant, and typical (not a rare extreme case)",
     ["It is dramatic but unusual", "It is about the speaker only", "It is invented for effect"],
     "Typical real examples generalize honestly; extreme or fake cases collapse under scrutiny.", None),
    ("How should you respond to hostile questions calmly?", "Repeat the question neutrally, then answer its substance",
     ["Match the hostility", "Refuse all questions", "Attack the questioner's motives"],
     "Neutralizing tone and answering substance keeps your credibility while defusing heat.", None),
    ("Which structure suits persuading a busy listener?", "Conclusion first, then two strong reasons",
     ["A 10-minute story before the point", "Background lecture first", "Hints and suspense"],
     "Busy audiences need the headline up front; support follows for those who want it.", None),
    ("What is the risk of overusing emotional appeals?", "Audiences feel manipulated and distrust you later",
     ["It makes facts unnecessary", "Emotions never backfire", "It speeds every decision safely"],
     "Emotional overload without evidence reads as manipulation and damages trust.", None),
    ("Which shows respect for a listener's intelligence?", "Explaining reasoning, not just demanding agreement",
     ["Repeating slogans louder", "Hiding weak points entirely", "Flattery without content"],
     "Transparent reasoning invites genuine agreement instead of coerced nods.", None),
    ("When persuading in writing, what should each paragraph do?", "Advance one clear idea with support",
     ["Mix five unrelated topics", "Repeat the introduction", "List random facts"],
     "One-idea paragraphs keep readers oriented and convinced step by step.", None),
    ("Which listener cue suggests you should slow down and clarify?", "Furrowed brows or 'wait, what?' responses",
     ["Nodding and note-taking", "Smiling agreement", "Leaning in with questions answered"],
     "Confusion signals mean your message needs simpler steps before moving on.", None),
    ("What is the honest use of humor in persuasion?", "To relax the audience and highlight a point kindly",
     ["To mock the opposing side", "To distract from weak evidence", "To insult skeptics softly"],
     "Kind humor builds rapport; hostile humor creates enemies and distrust.", None),
    ("Which is the strongest answer to 'Why should I care?'", "Connecting the topic to the listener's own goals or values",
     ["'Because I said so.'", "'Everyone must care.'", "'It's complicated, never mind.'"],
     "Relevance to the listener's life converts indifference into engagement.", None),
    ("Before a persuasive talk, the best preparation is ____.", "Knowing your audience's concerns and preparing answers to them",
     ["Memorizing only your favorite lines", "Ignoring possible objections", "Planning to speak faster"],
     "Anticipating objections turns Q&A from ambush into showcase.", None),
    ("Which closing technique invites genuine agreement?", "Asking for a small, concrete commitment they can actually keep",
     ["Demanding instant total loyalty", "Guilt about wasted time", "Threatening to leave"],
     "Small real commitments grow into larger voluntary support over time.", None),
]

UNSTOPPABLE_EXTRA = [
    ("Which is a keystone question for building any new habit?", "'When and where exactly will I do it?'",
     ["'Who can do it for me?'", "'Why do habits matter?'", "'What reward can I skip?'"],
     "Implementation intentions (specific time + place) dramatically increase habit follow-through.", None),
    ("What does 'deep work' mean?", "Long stretches of distraction-free focus on demanding tasks",
     ["Working late while checking messages", "Doing shallow admin all day", "Multitasking three projects"],
     "Deep work produces high-value results; constant interruption keeps work shallow.", None),
    ("Which is the best way to recover from a missed habit day?", "Resume the very next scheduled session without self-punishment",
     ["Restart the whole plan from zero", "Quit because the streak broke", "Double the next session harshly"],
     "Missing once is noise; self-punishment spirals are what actually break streaks.", None),
    ("How does an unstoppable person choose what to say NO to?", "Protect time for top priorities; decline what doesn't serve them",
     ["Say yes to everything politely", "Say no to everything always", "Let others decide entirely"],
     "Every yes costs time from something else; guarding priorities requires selective noes.", None),
    ("What is the purpose of a 'pre-mortem' before a big effort?", "Imagining how it could fail, then preventing those failures now",
     ["Predicting success only", "Canceling the plan early", "Blaming future teammates"],
     "Pre-mortems surface risks early so you can design around them.", None),
    ("Which behavior shows identity-level commitment?", "'I'm a runner' - training even on low-motivation days",
     ["'I sometimes jog if the weather is perfect'", "'I own running shoes'", "'I watch marathons'"],
     "Identity claims ('I am...') drive consistent action better than wishful 'I want to...'.", None),
    ("What is the '10-minute rule' for hard tasks?", "Commit to just 10 minutes; usually momentum continues past it",
     ["Work exactly 10 minutes then stop always", "Procrastinate 10 more minutes", "Reward yourself after 10 seconds"],
     "Lowering the start threshold defeats procrastination; starting is 80% of the battle.", None),
    ("Which environment tweak most helps phone-free studying?", "Putting the phone in another room, not just face-down",
     ["Keeping it lit beside the book", "Holding it 'just in case'", "Setting 30 alarms as reminders"],
     "Out of sight beats willpower; visible phones drain attention even unused.", None),
    ("How do unstoppable learners handle a plateau (no visible progress)?", "Change the method: new drills, feedback, or rest - not quit",
     ["Conclude they lack talent", "Repeat the identical failing routine", "Stop measuring progress"],
     "Plateaus mean the current approach maxed out; vary inputs to break through.", None),
    ("What is the '5-second rule' popularized for action-taking?", "Count 5-4-3-2-1, then physically move before doubts grow",
     ["Wait 5 hours to decide", "Sleep 5 minutes before tasks", "Give yourself 5 excuses"],
     "The countdown interrupts hesitation loops and launches action.", None),
    ("Which weekly review question drives the most growth?", "'What did I avoid this week, and why?'",
     ["'Who annoyed me most?'", "'What did others do wrong?'", "'How lucky was I?'"],
     "Avoidance reveals fears and friction - fixing them unlocks next week's progress.", None),
    ("What distinguishes discipline from motivation?", "Discipline is a trained behavior; motivation is a passing feeling",
     ["They are the same thing", "Discipline is genetic only", "Motivation is more reliable always"],
     "Feelings fluctuate; trained routines perform regardless - that's the unstoppable edge.", None),
]

OHS_EXTRA = [
    ("Which OHS practice applies to compressed gas cylinders in a shop?", "Store upright, secured, with valve caps on",
     ["Lay them rolling on the floor", "Store near heat sources", "Leave valves open for air"],
     "Secured upright storage prevents cylinders from falling and becoming dangerous projectiles.", None),
    ("What is the correct action when a safety guard is missing from a machine?", "Stop using the machine and report it before continuing",
     ["Use it carefully anyway", "Make a paper guard", "Let the fastest worker use it"],
     "Missing guards expose workers to moving parts; machines stay out of service until fixed.", None),
    ("Which practice reduces slip hazards in a computer shop?", "Cleaning spills immediately and using 'wet floor' signs",
     ["Stepping over spills", "Mopping only at closing", "Walking faster over wet areas"],
     "Immediate cleanup plus warning signs prevents the most common shop injuries.", None),
    ("Which is correct chemical safety when using isopropyl alcohol for cleaning?", "Ventilate the area, keep away from sparks, and cap the bottle",
     ["Use next to an open flame", "Store in a hot sunny window", "Leave containers open overnight"],
     "Alcohol vapors are flammable and irritating; ventilation and sealed storage are required.", None),
    ("What does a Material Safety Data Sheet (MSDS/SDS) provide?", "Hazard, handling, and first-aid information for chemicals",
     ["Warranty terms for tools", "A price list", "Network diagrams"],
     "SDS sheets tell workers exactly how to use, store, and respond to exposures for each chemical.", None),
    ("Which behavior violates electrical OHS in a lab?", "Daisy-chaining multiple extension cords to reach an outlet",
     ["Using one properly rated power strip", "Plugging directly into a wall outlet", "Replacing a short cord with a longer rated one"],
     "Chained cords overheat and fail; use a single properly rated cord or relocate equipment.", None),
    ("When two people must carry a long item (like a desk), they should ____.", "Lift together on a count, walk in step, and communicate turns",
     ["Lift whenever each feels ready", "Carry blind around corners fast", "Let the shorter person carry the heavy end"],
     "Coordinated team lifting prevents sudden load shifts and back injuries.", None),
    ("Which first-aid item must a computer shop keep stocked for cuts from sheet-metal cases?", "Bandages and antiseptic in the first-aid kit",
     ["Super glue only", "Duct tape", "Nothing - cases never cut"],
     "Case edges cause common minor cuts; stocked first aid enables immediate care.", None),
    ("Which OHS rule applies to eating areas in a technical shop?", "Eat only in designated areas away from chemicals and equipment",
     ["Eat at the workbench between tasks", "Store snacks in tool drawers", "Drink soda near the solder station"],
     "Separating food zones prevents ingestion of solder, dust, and solvent residues.", None),
    ("What is the correct response to a small chemical splash in the eye?", "Rinse with clean water or eyewash for 15+ minutes and seek medical help",
     ["Rub the eye firmly", "Apply alcohol to disinfect", "Wait to see if it improves tomorrow"],
     "Immediate prolonged flushing limits chemical eye damage; always follow up medically.", None),
    ("Which practice keeps emergency exits effective?", "Never block exits or extinguishers with boxes or furniture",
     ["Store spares in front of exits", "Hang coats on extinguishers", "Lock exits during class"],
     "Clear exits and visible extinguishers save seconds - and lives - during emergencies.", None),
    ("Which statement about PPE is correct?", "PPE is the last line of defense after removing or controlling the hazard",
     ["PPE replaces all other safety steps", "PPE makes every task risk-free", "PPE is optional if you are careful"],
     "The hierarchy of controls: eliminate, substitute, engineer, administer - then PPE.", None),
]

WIN_EXTRA = [
    ("Which keyboard shortcut opens the Windows Settings app quickly?", "Windows key + I",
     ["Ctrl + Alt + Tab", "Alt + F4", "Windows key + R only"],
     "Win+I opens Settings; Win+R opens the Run dialog.", None),
    ("What does the Windows 'diskpart' command manage?", "Disks, partitions, and volumes from the command line",
     ["Network cables", "Printer queues", "User passwords"],
     "diskpart creates, deletes, and formats partitions - used in setup and recovery.", None),
    ("Which tool migrates files and settings from an old PC to a new Windows install?", "Windows Easy Transfer / manual backup-restore",
     ["Task Manager", "Disk Cleanup only", "Magnifier"],
     "Backup-and-restore of user profiles moves documents, favorites, and settings.", None),
    ("What is the default file system Windows formats a new USB flash drive as (for compatibility)?", "FAT32 (or exFAT for large drives)",
     ["NTFS always", "EXT4", "APFS"],
     "FAT32/exFAT work across devices; NTFS is best for internal Windows drives.", None),
    ("Which setup screen asks for the computer name and workgroup/domain?", "The system/account configuration step (OOBE or sysprep for deployments)",
     ["The license screen", "The disk selection screen", "The boot menu"],
     "Naming happens late in setup; enterprises automate it via sysprep/unattend files.", None),
    ("What does the 'Repair' option in Windows Recovery Environment offer?", "Startup Repair, System Restore, Command Prompt, and uninstall updates",
     ["A full automatic reinstall always", "Virus definitions only", "A BIOS update"],
     "WinRE bundles multiple recovery tools for non-destructive repair attempts.", None),
    ("Which Windows feature rolls back a problematic driver or update?", "System Restore or 'Uninstall Updates' in recovery",
     ["Defragmenter", "ReadyBoost", "Aero Shake"],
     "Restore points and update removal undo changes that broke the system.", None),
    ("What is an 'answer file' (unattend.xml) used for?", "Automating Windows setup answers for deployments",
     ["Storing Wi-Fi passwords only", "Answering email", "Backing up photos"],
     "Unattend files pre-answer OOBE prompts so many PCs install identically without typing.", None),
    ("Which edition feature allows joining an Active Directory domain?", "Windows Pro / Enterprise",
     ["Windows Home", "Windows S mode on Home", "Any edition equally"],
     "Domain joining requires Pro or higher editions.", None),
    ("What does 'S mode' in Windows restrict?", "Installing apps only from the Microsoft Store for security",
     ["Internet access", "Screen brightness", "Mouse usage"],
     "S mode locks app sources to the Store; switching out is one-way.", None),
    ("Which utility shows which programs launch at boot and lets you disable them?", "Task Manager > Startup apps",
     ["Notepad", "Paint 3D", "Sound settings"],
     "Trimming startup apps speeds up boot and login noticeably.", None),
    ("After cloning a drive to a larger disk, which step makes Windows use the full space?", "Extend the partition into the unallocated space (Disk Management/diskpart)",
     ["Reinstall Windows always", "Nothing - it extends itself instantly", "Defragment the old drive"],
     "Clones copy the original partition size; extending reclaims the leftover unallocated area.", None),
]

ASM_EXTRA = [
    ("Which motherboard connector powers case cooling fans?", "The 3-pin or 4-pin SYS_FAN / CHA_FAN headers",
     ["The 24-pin ATX connector", "SATA ports", "Front USB header"],
     "Fan headers supply power and (4-pin) speed control for chassis fans.", None),
    ("When installing a CPU into an LGA socket, what should you do first?", "Lift the socket lever and align the notches before lowering the CPU",
     ["Press the CPU in at an angle", "Force it until it clicks", "Apply paste to the socket pins"],
     "The lever opens the load plate; alignment notches guarantee correct orientation.", None),
    ("Which RAM feature prevents inserting a DDR module backwards?", "The notch (keying slot) on the module edge",
     ["The label sticker", "The heatsink color", "The module weight"],
     "The notch matches a rib in the slot, so wrong orientation simply won't fit.", None),
    ("Why should dual-channel RAM be installed in matching-color slots?", "It enables dual-channel mode for better memory performance",
     ["Colors are purely decorative", "It prevents overheating", "It reduces power use to zero"],
     "Matching slots (per the manual) pair the modules for dual-channel bandwidth.", None),
    ("What is the purpose of the small lever on a SATA connector?", "It locks the cable so it does not slip out",
     ["It increases speed", "It grounds the drive", "It is a decorative clip"],
     "Press the metal/plastic latch when removing; forcing it breaks the lock.", None),
    ("Which action can crack a motherboard?", "Tightening the CPU cooler with uneven, excessive force",
     ["Using a pea-sized thermal paste dot", "Seating RAM with even pressure", "Installing standoffs first"],
     "Tighten cooler screws gradually in a cross pattern to spread pressure evenly.", None),
    ("Where does the CPU 8-pin (EPS) power cable connect?", "The 8-pin socket near the CPU, usually at the board's top-left",
     ["Any PCIe slot", "The 24-pin connector", "Front audio header"],
     "Do not confuse it with PCIe 8-pin - the EPS plug keys differently and sits by the CPU.", None),
    ("Which step prevents a video card from sagging and stressing its slot?", "Secure the bracket screw (and a support bracket for heavy cards)",
     ["Leave it floating", "Tape it to the side panel", "Lean the case backwards"],
     "The bracket screw anchors the card; heavy GPUs benefit from support brackets.", None),
    ("What does a long single beep (or beep code) at power-on usually indicate?", "A hardware issue reported by POST (meaning varies by BIOS brand)",
     ["Normal successful boot", "The OS is loading", "The monitor is asleep"],
     "Consult the motherboard manual's beep-code table to identify the failing part.", None),
    ("Which is correct for installing a 2.5-inch SSD in a desktop case?", "Mount it in a 2.5-inch bay or adapter, then connect SATA data and power",
     ["Glue it to the case floor", "Connect only the data cable", "Install it inside the PSU shroud loose"],
     "Secure mounting plus both cables (data + power) completes the installation.", None),
    ("Why are case standoffs usually brass or nylon?", "They insulate or safely ground the board while preventing shorts",
     ["They look premium", "They conduct maximum current", "They are magnetic"],
     "Correct standoffs keep board contacts clear of the metal tray.", None),
    ("Which tool helps retrieve a dropped screw inside a case?", "A magnetic screwdriver or magnetic pickup tool",
     ["Shaking the case upside down over the motherboard", "Pouring water to float it out", "Blowing hard repeatedly"],
     "Magnetic pickup retrieves screws safely; loose metal inside a case risks shorts.", None),
    ("What should be connected LAST when assembling a PC?", "The power cord (after everything else is verified)",
     ["The CPU fan", "The 24-pin connector", "The front panel switch"],
     "Connecting mains power last, after inspection, is the safest sequence.", None),
    ("Which check confirms RAM is fully seated?", "Both side clips snap back into the module notches",
     ["The module wobbles slightly", "The sticker faces outward", "The module is warm"],
     "Engaged clips mean the DIMM is locked and contacts are fully mated.", None),
    ("What is the function of the rear case fan in a typical airflow design?", "Exhaust - it pulls hot air out of the case",
     ["It pushes cold air in over the GPU", "It cools the PSU directly", "It inflates the case"],
     "Standard flow: front/bottom intake, rear/top exhaust, moving cool air across hot parts.", None),
    ("Which mistake can make a new build show no display?", "Monitor plugged into the motherboard port while a video card is installed",
     ["Using an HDMI cable", "Booting with the side panel on", "Installing one RAM stick in slot A2"],
     "With a GPU installed, displays should connect to the GPU's ports, not the board's.", None),
    ("Which practice protects the CPU socket pins during installation?", "Never touch or drop anything into the socket; keep the cover on until installation",
     ["Test pins with a pen", "Clean pins with a knife", "Store the board socket-down on foam"],
     "Bent LGA pins are a leading cause of dead boards; handle the socket area with care.", None),
    ("What does the 'PWR_SW' front-panel cable do?", "Connects the case power button to the motherboard so it can turn the system on",
     ["Powers the CPU directly", "Controls the monitor", "Resets the BIOS battery"],
     "Polarity usually doesn't matter for switches; see the manual for the exact header pins.", None),
    ("Which action is required before sliding the motherboard into the case?", "Install the correct I/O shield and all standoffs matching the board's holes",
     ["Skip the I/O shield for airflow", "Use standoffs only where convenient", "Apply paste to the case tray"],
     "The I/O shield and standoff pattern prepare the case to accept the board safely.", None),
    ("Why should you test-boot a new build before final cable management?", "To catch problems while every component is still easy to reach",
     ["Cable management must come first always", "Test-booting damages new parts", "It is only for used parts"],
     "Fixing a no-POST build is far easier before everything is zip-tied and tucked.", None),
    ("Which screwdriver size is most common for PC case screws?", "#2 Phillips",
     ["#00 Phillips", "Torx T20", "Flat-head 5 mm"],
     "A #2 Phillips fits the majority of case, PSU, and drive screws.", None),
    ("When removing a stubborn expansion card, the correct approach is ____.", "Release the slot clip, remove the bracket screw, and rock gently straight up",
     ["Pry against the motherboard with a screwdriver", "Pull at a steep angle hard", "Cut the bracket"],
     "Clip release plus gentle straight rocking protects both the slot and the card.", None),
    ("What is the purpose of a PSU shroud in modern cases?", "It hides cables/PSU and helps separate hot PSU air from component airflow",
     ["It amplifies fan noise", "It holds the motherboard", "It stores extra RAM"],
     "Shrouds improve aesthetics and thermal separation in modern layouts.", None),
    ("Which action avoids static buildup while assembling on carpet?", "Work on a hard floor with an anti-static mat; avoid carpet entirely",
     ["Shuffle feet to discharge", "Assemble on a wool blanket", "Spray water mist around"],
     "Carpet generates static; hard surfaces with grounded mats are the safe workspace.", None),
    ("Which post-assembly habit extends component life?", "Keeping vents unblocked and dust filters cleaned regularly",
     ["Placing the tower deep in a closed cabinet", "Covering vents with stickers", "Removing all fans for silence"],
     "Cool, dust-free airflow is the simplest longevity upgrade for any PC.", None),
    ("Which is correct about mixing old and new RAM modules?", "Match type (DDR generation) first; mixed speeds run at the slowest module",
     ["Any RAM fits any slot", "Mixing DDR3 and DDR4 is fine", "Speeds always run at the fastest"],
     "DDR generations are physically incompatible; mixed kits downclock to the lowest common speed.", None),
]


def pascal_numeric(seed):
    """Procedurally generate unique P = F/A and F = P x A questions."""
    import random
    rng = random.Random(seed)
    out = []
    seen = set()
    while len(out) < 16:
        style = rng.choice(["P", "F", "A"])
        if style == "P":
            a = rng.choice([2, 4, 5, 8, 10, 20, 25, 50])
            f = a * rng.choice([3, 4, 6, 7, 8, 9, 12, 15])
            p = f // a
            q = f"A force of {f} N acts on an area of {a} m2. What pressure is produced?"
            ans = f"{p} Pa"
            distr = [f"{p + rng.choice([2, 3, 5])} Pa", f"{max(1, p - rng.choice([1, 2, 3]))} Pa", f"{f + a} Pa"]
            exp = f"P = F / A = {f} N / {a} m2 = {p} Pa."
        elif style == "F":
            p = rng.choice([20, 50, 100, 150, 200, 250, 400])
            a = rng.choice([2, 3, 4, 5, 6, 8])
            f = p * a
            q = f"A confined fluid at {p} Pa pushes on a piston of area {a} m2. What force results?"
            ans = f"{f} N"
            distr = [f"{f + p} N", f"{f - a} N", f"{p + a} N"]
            exp = f"F = P x A = {p} Pa x {a} m2 = {f} N."
        else:
            f = rng.choice([40, 60, 90, 120, 180, 240])
            p = rng.choice([10, 20, 30, 40, 60])
            while f % p != 0:
                p = rng.choice([10, 20, 30, 40, 60])
            a = f // p
            q = f"A force of {f} N produces a pressure of {p} Pa. Over what area is it applied?"
            ans = f"{a} m2"
            distr = [f"{a + 1} m2", f"{max(1, a - 1)} m2", f"{a * 2} m2"]
            exp = f"A = F / P = {f} N / {p} Pa = {a} m2."
        if q in seen:
            continue
        seen.add(q)
        out.append((q, ans, distr, exp, None))
    return out
